ALTER TABLE public.video_playback_logs DROP CONSTRAINT IF EXISTS video_playback_logs_building_id_fkey;
ALTER TABLE public.video_playback_logs DROP CONSTRAINT IF EXISTS video_playback_logs_video_id_fkey;
ALTER TABLE public.video_playback_logs DROP CONSTRAINT IF EXISTS video_playback_logs_pedido_id_fkey;