ALTER TABLE public.webhook_logs ADD COLUMN IF NOT EXISTS provider text, ADD COLUMN IF NOT EXISTS webhook_id text, ADD COLUMN IF NOT EXISTS event_type text, ADD COLUMN IF NOT EXISTS processed_at timestamptz, ADD COLUMN IF NOT EXISTS attempts integer NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS error_message text, ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS webhook_logs_provider_webhook_id_uidx ON public.webhook_logs(provider,webhook_id) WHERE provider IS NOT NULL AND webhook_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS webhook_logs_pending_idx ON public.webhook_logs(status,created_at) WHERE provider='asaas';
ALTER TABLE public.sync_runs ADD COLUMN IF NOT EXISTS source text, ADD COLUMN IF NOT EXISTS state text NOT NULL DEFAULT 'running', ADD COLUMN IF NOT EXISTS pages_count integer NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS items_count integer NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS last_success_at timestamptz, ADD COLUMN IF NOT EXISTS window_start date, ADD COLUMN IF NOT EXISTS window_end date, ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS sync_runs_source_started_idx ON public.sync_runs(source,started_at DESC);
CREATE TABLE public.financial_baselines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), captured_at timestamptz NOT NULL DEFAULT now(), summary jsonb NOT NULL, note text NOT NULL DEFAULT 'Pre-ingestion technical baseline');
GRANT SELECT ON public.financial_baselines TO authenticated;
GRANT ALL ON public.financial_baselines TO service_role;
ALTER TABLE public.financial_baselines ENABLE ROW LEVEL SECURITY;
CREATE POLICY financial_baselines_admin_read ON public.financial_baselines FOR SELECT TO authenticated USING (public.has_any_admin_role(auth.uid()));
DROP POLICY IF EXISTS "System can insert webhook_logs" ON public.webhook_logs;
DROP POLICY IF EXISTS "Admins can read webhook_logs" ON public.webhook_logs;
CREATE POLICY webhook_logs_admin_read ON public.webhook_logs FOR SELECT TO authenticated USING (public.has_any_admin_role(auth.uid()));
REVOKE ALL ON public.webhook_logs FROM anon, authenticated;
GRANT SELECT ON public.webhook_logs TO authenticated;
GRANT ALL ON public.webhook_logs TO service_role;
DROP POLICY IF EXISTS "Service role pode inserir transacoes_asaas" ON public.transacoes_asaas;
DROP POLICY IF EXISTS "Service role pode atualizar transacoes_asaas" ON public.transacoes_asaas;
DROP POLICY IF EXISTS "Admins podem visualizar transacoes_asaas" ON public.transacoes_asaas;
CREATE POLICY transacoes_asaas_admin_read ON public.transacoes_asaas FOR SELECT TO authenticated USING (public.has_any_admin_role(auth.uid()));
REVOKE ALL ON public.transacoes_asaas FROM anon, authenticated;
GRANT SELECT ON public.transacoes_asaas TO authenticated;
GRANT ALL ON public.transacoes_asaas TO service_role;
GRANT SELECT ON public.sync_runs TO authenticated;
GRANT ALL ON public.sync_runs TO service_role;
DROP POLICY IF EXISTS "Service role only access" ON public.sync_runs;
CREATE POLICY sync_runs_admin_read ON public.sync_runs FOR SELECT TO authenticated USING (public.has_any_admin_role(auth.uid()));