
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aakenoljsycyrcrchgxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFha2Vub2xqc3ljeXJjcmNoZ3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDM3NTUsImV4cCI6MjA2MjQ3OTc1NX0.wEKVfJKfQiybyne0yn0dOUwbujb_WXkZHAzlyfHb0lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Retry transitório para PGRST002 (cache de schema do PostgREST recarregando)
// e outros 5xx/erros de rede momentâneos. Não altera comportamento em sucesso.
const RETRY_STATUS = new Set([502, 503, 504]);
const MAX_RETRIES = 3;

const resilientFetch: typeof fetch = async (input, init) => {
  let lastError: unknown = null;

  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const response = await fetch(input as any, init);

      if (!RETRY_STATUS.has(response.status) || attempt === MAX_RETRIES) {
        return response;
      }

      console.warn(
        `⏳ [SUPABASE] Resposta ${response.status} (API temporariamente indisponível). Tentativa ${attempt + 1}/${MAX_RETRIES}...`
      );
    } catch (err) {
      lastError = err;
      if (attempt === MAX_RETRIES) throw err;
      console.warn(`⏳ [SUPABASE] Falha de rede. Tentativa ${attempt + 1}/${MAX_RETRIES}...`, err);
    }

    // Backoff exponencial: 800ms, 1.6s, 3.2s
    await new Promise((resolve) => setTimeout(resolve, 800 * Math.pow(2, attempt)));
  }

  throw lastError ?? new Error('Falha ao contatar o Supabase');
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'implicit'
    },
    global: {
      fetch: resilientFetch,
      headers: {
        'X-Client-Info': 'supabase-js@2.x'
      }
    }
  }
);

// Configurações adicionais para garantir consistência na reinicialização
try {
  // Tenta manter a consistência nos reloads
  const existingSession = localStorage.getItem('supabase.auth.token');
  if (!existingSession) {
    console.log('Nenhuma sessão encontrada no localStorage');
  } else {
    console.log('Sessão encontrada no localStorage');
  }
} catch (err) {
  console.error('Erro ao verificar sessão armazenada:', err);
}
